### PR TITLE
localization update with 1.0.3

### PR DESCRIPTION
**Pull request by urgiv**
update zh-hans
also at en-US line 12, should be  "See Genisis Conduit Prefix **Whitelist** to learn"

### CODE REVIEW

**Comment by urgiv** [comment]
For ArtificerMod v1.1: https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/commit/a39103874ceda414f838e0dd5ee4b09aa4e80a91
also, what else mods have been updated since last localization

**Review by BlockCrusader — APPROVED** [review]
Cool, thanks for the quick update (As well as fixing the oversight in one of the english keys). I'll try and release this alongside an urgent bug-fix early today.

I think the only other mod that could use a localization update is Weapon Augments. I don't think the GitHub repo is up-to-date so utilize the tML extract localization function once more.

**Comment by urgiv** [comment]
For WeaponAugs v1.1: https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/commit/ae58646047e3bd20625409d71a14a413cf601878
zh-Hans and workshop description

**Comment by BlockCrusader** [comment]
Weapon Augments localization is now up-to-date on the Workshop

**Comment by urgiv** [comment]
For Arsenal_Mod v1.4.3.3: https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/commit/6ac55f04c5b1df5491ba23070b5fbf01824fce49
really impressive mod with such abundant content

**Comment by BlockCrusader** [comment]
Thx for the kind words and the localization! It's now been released onto the Workshop

**Pull request merged**
